[package]
name = "project-eular-rust"
version = "0.1.0"
authors = ["Nikhil Yekhe <yendenikhil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
